variables:
  GIT_STRATEGY: fetch

build_develop:
  stage: build
  only:
    - master
  tags:
    - optimeal
    - develop
    - app
  script:
    - npm ci
    - ng build --configuration=production
    - cp -r -force www/* $OUTPUT_FOLDER
